/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p41-gfeadfc5e
 *
 * Project: 'FSBL.Debug+STM32N657X0HxQ' 
 * Target:  'Debug+STM32N657X0HxQ' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32n6xx.h"


#endif /* RTE_COMPONENTS_H */
